add -i to add_to_bin

diff --git a/add_to_bin b/add_to_bin
--- a/add_to_bin
+++ b/add_to_bin
@@ -3,6 +3,15 @@
 shopt -s extglob nullglob
 force=0
 verbose=0
+interactive=0
+
+# prints confirmation prompt, returns according to the response
+confirm() {
+  local -l reply
+
+  read -p "$1 [Y/n] " reply > /dev/tty < /dev/tty
+  [[ -z $reply || $reply = y?(es) ]]
+}
 
 # err and exit
 die() {
@@ -10,6 +19,26 @@ die() {
   exit 1
 } >&2
 
+# adds '.N' to a filename, sans extension, until it doesn't exist
+noclobber() {
+  local out=$1 i=0
+
+  if [[ $out = *+([^/]).*([^/]) ]]; then
+    local base=${1%.*} ext=${1##*.}
+
+    while [[ -e $out ]]; do
+      out=$base.$((++i)).$ext
+    done
+  else
+    while [[ -e $out ]]; do
+      out=$1.$((++i))
+    done
+  fi
+
+  printf '%s\n' "$out"
+}
+
+# print usage
 usage() {
 cat <<'EOF'
 add_to_bin [DIR]
@@ -18,13 +47,14 @@ Compiles all of the *.c files, and creates hard links to all of the scripts, in
 the current dir into DIR (~/bin by default)
 
  Options:
-  -h, --help      Display this help and exit
-  -f, --force     Overwrite existing files
-  -v, --verbose   Output more
+  -h, --help          Display this help and exit
+  -f, --force         Overwrite existing files
+  -i, --interactive   Prompt for new filename when file exists
+  -v, --verbose       Output more
 EOF
 }
 
-# iterate over options, break -ab into -a -b and --foo=bar into --foo bar
+# iterate over options, break -ab into -a -b
 unset options
 while (($#)); do
   case $1 in
@@ -33,7 +63,6 @@ while (($#)); do
         options+=("-${1:i:1}")
       done
       ;;
-    --?*=*) options+=("${1%%=*}" "${1#*=}");;
     --) options+=(--endopts);;
     *) options+=("$1");;
   esac
@@ -48,6 +77,7 @@ while [[ $1 = -?* ]]; do
   case $1 in
     -h|--help) usage >&2; exit 0;;
     -f|--force) force=1;;
+    -i|--interactive) interactive=1;;
     -v|--verbose) verbose=1;;
     --endopts) shift; break;;
     *) die "invalid option: $1";;
@@ -77,15 +107,19 @@ for f in !(add_to_bin); do
       printf 'compiling %s, output file %s\n' "$f" "$out"
     fi
 
-    # if the output file exists, rm if force is set or err and skip
-    if [[ -e $out ]]; then
+    # if the output file exists, rm if force is set, prompt if interactive is
+    # set, or err and skip
+    while [[ -e $out ]]; do
       if ((force)); then
         rm -f "$out"
+      elif ((interactive)) && confirm "$out exists, change filename?"; then
+        printf -v default %q "$(noclobber "$out")"
+        read -ei "$default" out
       else
         printf '%s exists, skipping compiling %s\n' "$out" "$f" >&2
-        continue
+        continue 2
       fi
-    fi
+    done
 
     case $f in
       # if it's a url_* tool, compile with -lcurl
@@ -116,20 +150,28 @@ for f in !(add_to_bin); do
       printf 'creating hard link to %s\n' "$f"
     fi
 
-    # if the output file exists, rm if force is set or err and skip
-    if [[ -e $target/$f ]]; then
+    out=$target/$f
+
+    # if the output file exists, rm if force is set, prompt if interactive is
+    # set, or err and skip
+    while [[ -e $out ]]; do
       if ((force)); then
-        rm -f "$target/$f"
+        rm -f "$out"
+      elif ((interactive)) && confirm "$out exists, change filename?"; then
+        printf -v default %q "$(noclobber "$out")"
+        read -ei "$default" out
       else
         printf '%s exists, skipping creating a hard link to %s\n' \
-               "$target/$f" "$f" >&2
-        continue
+               "$out" "$f" >&2
+        continue 2
       fi
-    fi
+    done
 
     # create hard link
-    ln -t "$target" "$f"
+    if ! ln "$f" "$out"; then
+      die "error creating hard link $out"
+    fi
   fi
-  # files that aren't *.c, nor executable, are README or a template/lib
-  # they get ignored
+  # files that aren't *.c, nor executable, are README or a template/lib/etc
+  # get ignored
 done
