add sh to languages, create add_path function that folds PATH on ":" and trims the PATH assignment to 80 char lines if possible

diff --git a/newscript b/newscript
--- a/newscript
+++ b/newscript
@@ -9,15 +9,62 @@ lang=bash
 edit=0
 toedit=()
 
+# add a PATH assignment and export to the script, based on the curent PATH
+# splits on colons so that the lines are truncated to 80 chars
+add_path() {
+  local q=\' IFS=: cur=0 path len i elements
+
+  # split PATH (with escaped single quotes) into array on ":"
+  IFS=: read -ra path <<<"${PATH//$q/\\$q}"
+  elements=${#path[@]}
+
+  # iterate over array elements, adding the lengths until the line is too long
+  for ((i=0, len=0; i<=elements && len<=74; i++)); do
+    ((len += ${#path[i]} + 1))
+  done
+  ((i--))
+
+  # if one element is too long, use it anyway
+  if ((cur < elements && cur == i)); then
+    ((i++))
+  fi
+
+  # print the assignment, with all of the elements up to "i"
+  printf "PATH='%s'\n" "${path[*]:cur:i-cur}"
+  # cur is the element at which the line becomes too long
+  cur=$i
+
+  # continue looping over the indices, doing the same, until PATH is exhausted
+  until ((cur >= elements)); do
+    for ((i=cur, len=0; len<=72 && i<=elements; i++)); do
+      ((len += ${#path[i]} + 1))
+    done
+    ((i--))
+
+    if ((cur < elements && cur == i)); then
+      ((i++))
+    fi
+
+    printf "PATH+=':%s'\n" "${path[*]:cur:i-cur}"
+    cur=$i
+  done
+
+  # print the export line
+  printf "%s\n\n" 'export PATH'
+}
+
+# print error and exit
 die() {
   printf '%s\n' "$@"
   exit 1
 } >&2
 
+# print error, do not exit
 err() {
   printf '%s\n' "$@"
 } >&2
 
+# open VISUAL, EDITOR, or "vi", in that order
 editor() {
   if [[ $VISUAL ]]; then
     $VISUAL "$@"
@@ -26,12 +73,23 @@ editor() {
   fi
 }
 
+# adds '.N' to a filename, sans extension, until it doesn't exist
 noclobber() {
-  local new=$1 i=0
-  while [[ -e $new ]]; do
-    new=$1$((++i))
-  done
-  printf '%s\n' "$new"
+  local out=$1 i=0
+
+  if [[ $1 = *+([^/]).*([^/]) ]]; then
+    local base=${1%.*} ext=${1##*.}
+    
+    while [[ -e $out ]]; do
+      out=$base.$((++i)).$ext
+    done
+  else
+    while [[ -e $out ]]; do
+      out=$1.$((++i))
+    done
+  fi
+
+  printf '%s\n' "$out"
 }
 
 usage() {
@@ -42,14 +100,14 @@ newscript [OPTIONS] NAME [...]
   -h, --help              display this help and exit
   -l, --language LANG     specify the language LANG, default is bash
   -s, --shebang SHEBANG   provide the entire shebang as an arg, SHEBANG
-  -c,  --cron             add a your current PATH to the beginning of the script
-                          » only available with bash
+  -c,  --cron             add a your current PATH to the beginning of the
+                          script. only available with -l bash (default), or sh
   -n, --no-clobber        prepends a number to the end of each existing NAME
                           instead of erring
   -e, --edit              open created files in a text editor
 
  Available languages for LANG are:
-  bash, awk, sed, perl, python
+  bash, sh, awk, sed, perl, python
 EOF
 }
 
@@ -108,6 +166,7 @@ while [[ $1 = -?* ]]; do
     -h|--help) usage; exit 0;;
     *) die "invalid option: $1";;
   esac
+
   shift
 done
 
@@ -126,10 +185,11 @@ if ((fullshebang)); then
   esac
 else
   case $lang in
-    bash) shebang='#!/bin/bash';;
-    awk) shebang='#!/bin/awk -f';;
-    sed) shebang='#!/bin/sed -f';;
-    perl) shebang='#!/usr/bin/perl';;
+    bash)   shebang='#!/bin/bash';;
+    sh)     shebang='#!/bin/sh';;
+    awk)    shebang='#!/bin/awk -f';;
+    sed)    shebang='#!/bin/sed -f';;
+    perl)   shebang='#!/usr/bin/perl';;
     python) shebang='#!/usr/bin/python';;
   esac
 fi
@@ -150,7 +210,10 @@ for file; do
     case $lang in
       bash)
         printf '%s\n\n' 'shopt -s extglob nullglob'
-        ((cron)) && printf 'PATH=%s\n\n' "$PATH"
+        ((cron)) && add_path
+        ;;
+      sh)
+        ((cron)) && add_path
         ;;
       perl)
         printf '%s\n%s\n\n' 'use warnings;' 'use strict;'
@@ -158,7 +221,7 @@ for file; do
     esac
   } > "$file"
 
-  chmod +x "$file" || err "error making $file executable"
+  chmod +x -- "$file" || err "error making $file executable"
   toedit+=("$file")
 done
 
