add --maxdepth to update_gits

diff --git a/update_gits b/update_gits
--- a/update_gits
+++ b/update_gits
@@ -7,20 +7,24 @@
 # repositories in the highest level sub-directories. Requires GNU find.
 #
 #  Options:
-#   -r, --recursive     Search for repositories within DIR recursively
-#   -e, --exclude PATT  Do not check directories matching PATT, and do not
-#                       descend into them when searching recursively. PATT is a
-#                       shell pattern, as used for find -name. May be provided
-#                       multiple times to exclude multiple patterns
-#   -i, --ignore-case   Make any instance of PATT case insensitive
-#   -q, --quiet         Only output for repos that are updated
-#   -h, --help          Display this help and exit
+#   -r, --recursive       Search for repositories within DIR recursively
+#   -m, --maxdepth DEPTH  Limit recursiveness to DEPTH levels, just like GNU
+#                         find's -maxdepth option. Implies --recursive
+#   -e, --exclude PATT    Do not check directories matching PATT, and do not
+#                         descend into them when searching recursively. PATT is
+#                         a shell pattern, as used for find -name. May be
+#                         provided multiple times to exclude multiple patterns
+#   -i, --ignore-case     Make any instance of PATT case insensitive
+#   -q, --quiet           Only output for repos that are updated
+#   -h, --help            Display this help and exit
 
 
 
 # default global vars, shopts, etc
 shopt -s extglob nullglob
 recursive=0
+has_maxd=0
+maxdepth=1
 to_exclude=()
 icase=0
 quiet=0
@@ -34,20 +38,22 @@ current working directory if DIR is not provided. By default, only check for
 repositories in the highest level sub-directories. Requires GNU find.
 
  Options:
-  -r, --recursive     Search for repositories within DIR recursively
-  -e, --exclude PATT  Do not check directories matching PATT, and do not
-                      descend into them when searching recursively. PATT is a
-                      shell pattern, as used for find -name. May be provided
-                      multiple times to exclude multiple patterns
-  -i, --ignore-case   Make any instance of PATT case insensitive
-  -q, --quiet         Only output for repos that are updated
-  -h, --help          Display this help and exit
+  -r, --recursive       Search for repositories within DIR recursively
+  -m, --maxdepth DEPTH  Limit recursiveness to DEPTH levels, just like GNU
+                        find's -maxdepth option. Implies --recursive
+  -e, --exclude PATT    Do not check directories matching PATT, and do not
+                        descend into them when searching recursively. PATT is
+                        a shell pattern, as used for find -name. May be
+                        provided multiple times to exclude multiple patterns
+  -i, --ignore-case     Make any instance of PATT case insensitive
+  -q, --quiet           Only output for repos that are updated
+  -h, --help            Display this help and exit
 EOF
 }
 
 # option string, for short options.
 # very much like getopts, any option followed by a ':' takes a required arg
-optstring=re:iqh
+optstring=rm:e:iqh
 
 # iterate over options, breaking -ab into -a -b and --foo=bar into --foo bar
 # also turns -- into --endopts to avoid issues with things like '-o-', the '-'
@@ -83,9 +89,23 @@ unset options
 while [[ $1 = -?* ]]; do
   case $1 in
     -r|--recursive) recursive=1;;
+    -m|--maxdepth)
+      if [[ -z $2 ]]; then
+        printf 'No DEPTH provided for %s\n' "$1" >&2
+        exit 1
+      fi
+      if [[ $2 = *[!0-9]* ]]; then
+        printf 'Invalid DEPTH: %s\n' "$2" >&2
+        exit 1
+      fi
+      recursive=1
+      has_maxd=1
+      maxdepth=$2
+      shift
+      ;;
     -e|--exclude)
       if [[ -z $2 ]]; then
-        printf 'no PATT provided for %s\n' "$1" >&2
+        printf 'No PATT provided for %s\n' "$1" >&2
         exit 1
       fi
       to_exclude+=("$2")
@@ -95,17 +115,18 @@ while [[ $1 = -?* ]]; do
     -q|--quiet) quiet=1;;
     -h|--help) usage >&2; exit 0;;
     --endopts) shift; break;;
-    *) printf 'invalid option: %s\n' "$1" >&2; exit 1;;
+    *) printf 'Invalid option: %s\n' "$1" >&2; exit 1;;
   esac
 
   shift
 done
 
 # build the find options
-if ((recursive)); then
-  findopts=()
-else
-  findopts=(-maxdepth 2)
+findopts=()
+if ((!recursive)); then
+  findopts+=(-maxdepth 1)
+elif ((has_maxd)); then
+  findopts+=(-maxdepth "$maxdepth")
 fi
 
 if ((${#to_exclude[@]})); then
@@ -128,33 +149,40 @@ if ((${#to_exclude[@]})); then
   findopts+=(')' -prune -o)
 fi
 
-findopts+=(-type d -name .git -print0)
+findopts+=(
+-type d
+-exec test -f {}/.git/HEAD \; 
+-exec sh -c 'cd "$1" && git rev-parse 2>/dev/null' _ {} \;
+-print0
+)
 
 # run the find command, loop over each found directory
-while IFS= read -rd '' dir; do
+while IFS= read -rd '' repo; do
   # update the repo
   (
-    repo=${dir%/.git}
     if ! cd "$repo"; then
-      printf 'error changing into repo/directory: %s\n' "$repo" >&2
+      printf 'Error changing into repo/directory: %s\n' "$repo" >&2
       exit 1
     fi
 
     if ((quiet)); then
       if ! out=$(git pull); then
-        printf 'error updating repo/directory: %s\n' "$repo" >&2
+        printf 'Error updating repo/directory: %s\n\n' "$repo" >&2
         exit 1
       fi
-      if [[ $out != "Already up-to-date" ]]; then
+      if [[ $out != *"Already up-to-date"* ]]; then
         printf 'Updating repo/directory: %s\n' "$repo"
-        printf '%s\n' "$out"
+        printf '%s\n\n' "$out"
       fi
+
     else
       printf 'Updating repo/directory: %s\n' "$repo"
       if ! git pull; then
-        printf 'error updating repo/directory: %s\n' "$repo" >&2
+        printf 'Error updating repo/directory: %s\n\n' "$repo" >&2
         exit 1
       fi
+
+      echo
     fi
   )
 done < <(find "${@:-.}" "${findopts[@]}" 2>/dev/null)
